### ISSUE TITLE
Update für FVV 2018-11-07 benötigt

### ISSUE THREAD

**Issue by dragetd** [foss-ag/vortrag_fvv#5]
Wir brauchen eine Kurzversion (max. 1-2 Folien) wo wir den Tex-Code (nur Inhalt) an den FVV-Folienmenschen schicken.

**Comment by Lazalatin** [comment]
Ich werde dafür einen neuen Branch auschecken, für eine kürzere Version.

**Comment by Lazalatin** [comment]
Ergebnis findet sich im short_version branch.
